config/routes.rb
Rails3MongoidDevise::Application.routes.draw do

  resources :dayoffs

  resources :rawusers

  resources :timesheets

  resources :rawdata

  resources :employees

  resources :departments

  resources :timeshifts

  match "/rawdata-import"           => "rawdata#import"
  match "/rawusers-import"          => "rawusers#import"
  match "/rawusers-sync-pc"         => "rawusers#syncpc"
  match "/settings"                 => "settings#show"
  match "/settings/departments"     => "settings#departments"
  match "/settings/timeshifts"      => "settings#timeshifts"
  match "/settings/dayoffs"         => "settings#dayoffs"
  match "/settings/messages"        => "settings#messages"


  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  root :to => "home#index"
  resources :users, :only => [:show, :index]
end

app/models/employee.rb
class Employee
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  SYNC_TYPES = [:to_pc, :from_pc]

  paginates_per 5

  field :name, type: String
  field :employee_code, type: String
  field :work_from, type: Date
  field :gender, type: String
  field :status, type: String

  field :enroll_number, type: String
  field :machine_name, type: String
  field :machine_password, type: String
  field :machine_privilege, type: Integer
  field :machine_enabled, type: Boolean
  field :machine_card, type: String  

  validates_presence_of :name
  validates :enroll_number, presence: true, uniqueness: true

  embeds_many :employeeoffs
  has_many :timesheets
  belongs_to :user
  belongs_to :department
  belongs_to :timeshift

  def timed_rawlist(from, to)
    Rawdatum.timed_between(self.enroll_number, from, to)
  end

  class << self
    def synchronize(type)
      if (type == :to_pc)
        Rawuser.each do |raw|
          if where(enroll_number: raw.enroll_number).exists?
            e = find_by(enroll_number: raw.enroll_number)
            e.attributes = { machine_password: raw.password, machine_name: raw.name, machine_enabled: raw.enabled}
            e.save
          else
            create(enroll_number: raw.enroll_number,
                   name: raw.name,
                   machine_password: raw.password,
                   machine_enabled: raw.enabled,
                   machine_name: raw.name)
          end
        end
      else
      end
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="columns wat-cf">
<div class="column left">
  <!--div class="group">
    <%= f.label :_type, t("activerecord.attributes.employee._type", :default => " type"), :class => :label %>
    <%= f.text_field :_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :_id, t("activerecord.attributes.employee._id", :default => ""), :class => :label %>
    <%= f.text_field :_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div-->

  <div class="group">
    <%= f.label :name, t("activerecord.attributes.employee.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :department, t("activerecord.attributes.employee.department", :default => "Department"), :class => :label %>
    <%= f.text_field :department, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
</div>
<div class="column right">
  <div class="group">
    <%= f.label :work_from, t("activerecord.attributes.employee.work_from", :default => "Work from"), :class => :label %>
    <%= f.text_field :work_from, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
</div>
</div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), employees_path, :class => "text_button_padding link_button" %>
</div>

app/views/employees/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/employees/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", employees_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_employee_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_employee_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Employee</h2>
    <div class="inner">
      <%= form_for @employee, :url => employee_path(@employee), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/employees/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", employees_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_employee_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Employees</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>Name</th>
          <th>Gender</th>
          <th>Department</th>
          <th>Enroll Number</th>
          <!--th>
            <%= t("activerecord.attributes.employee._type", :default => t("activerecord.labels._type", :default => "_type")) %>
          </th-->
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @employees.each do |employee| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= employee.id %>
          </td>
          <td>
            <%= employee.name %>
          </td>
          <td>
            <%= employee.gender %>
          </td>
          <td>
            <%= employee.department %>
          </td>
          <td>
            <%= employee.enroll_number %>
          </td>
          <!--td>
            <%= link_to employee._type, employee_path(employee) %>
          </td-->
          <td>
            <%= employee.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", employee_path(employee) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_employee_path(employee) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", employee_path(employee), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @employees  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/employees/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", employees_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_employee_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Employee</h2>
    <div class="inner">
      <%#= render 'form' -%>
      <%= form_for :employee, :url => employees_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/employees/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", employees_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_employee_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", employee_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.employee._type", :default => t("activerecord.labels._type", :default => " type")) %>:</b>
          <%= @employee._type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.employee._id", :default => t("activerecord.labels._id", :default => "")) %>:</b>
          <%= @employee._id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.employee.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @employee.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.employee.department", :default => t("activerecord.labels.department", :default => "Department")) %>:</b>
          <%= @employee.department %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.employee.work_from", :default => t("activerecord.labels.work_from", :default => "Work from")) %>:</b>
          <%= @employee.work_from %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_employee_path(@employee), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), employee_path(@employee), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>