config/routes.rb
Rails3MongoidDevise::Application.routes.draw do

  resources :dayoffs

  resources :rawusers

  resources :timesheets

  resources :rawdata

  resources :employees

  resources :departments

  resources :timeshifts

  match "/rawdata-import"           => "rawdata#import"
  match "/rawusers-import"          => "rawusers#import"
  match "/rawusers-sync-pc"         => "rawusers#syncpc"
  match "/settings"                 => "settings#show"
  match "/settings/departments"     => "settings#departments"
  match "/settings/timeshifts"      => "settings#timeshifts"
  match "/settings/dayoffs"         => "settings#dayoffs"
  match "/settings/messages"        => "settings#messages"


  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  root :to => "home#index"
  resources :users, :only => [:show, :index]
end

app/models/rawuser.rb
class Rawuser
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  paginates_per 5

  field :machine_code, type: Integer
  field :enroll_number, type: String
  field :name, type: String
  field :password, type: String
  field :privilege, type: Integer
  field :enabled, type: Boolean
  field :fingers, type: Array

  class << self
    def import(ipaddr)
      zk = Zkemkeeper.new
      if zk.connect_net(ipaddr)
        zk.regevent()
        zk.readalluserid()
        zk.readalltemplate()
        rawuser = {}
        while (zk.ssr_getalluserinfo(1, rawuser))
          if where(enroll_number: rawuser[:dwenrollnumber]).exists?
            #1..10.each do |index|
            #  rawf = {}
            #  zk.getusertmpexstr(1, rawuser[:dwenrollnumber], index, rawf)
            #  rawuser[:fingers] << rawf[:tmpdata]
            #end

            create(machine_code: 1,
                   enroll_number: rawuser[:dwenrollnumber],
                   name: rawuser[:name],
                   password: rawuser[:password],
                   privilege: rawuser[:privilege],
                   enabled: rawuser[:enabled])
            
            rawuser = {}
          end
        end
        zk.disconnect()
        true
      else
        false
      end
    end
  end
end

app/controllers/rawusers_controller.rb
class RawusersController < ApplicationController
  # GET /rawusers
  # GET /rawusers.json
  def index
    @rawusers = Rawuser.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rawusers }
    end
  end

  # GET /rawusers/1
  # GET /rawusers/1.json
  def show
    @rawuser = Rawuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rawuser }
    end
  end

  # GET /rawusers/new
  # GET /rawusers/new.json
  def new
    @rawuser = Rawuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rawuser }
    end
  end

  # GET /rawusers/1/edit
  def edit
    @rawuser = Rawuser.find(params[:id])
  end

  # POST /rawusers
  # POST /rawusers.json
  def create
    @rawuser = Rawuser.new(params[:rawuser])

    respond_to do |format|
      if @rawuser.save
        format.html { redirect_to @rawuser, notice: 'Rawuser was successfully created.' }
        format.json { render json: @rawuser, status: :created, location: @rawuser }
      else
        format.html { render action: "new" }
        format.json { render json: @rawuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rawusers/1
  # PUT /rawusers/1.json
  def update
    @rawuser = Rawuser.find(params[:id])

    respond_to do |format|
      if @rawuser.update_attributes(params[:rawuser])
        format.html { redirect_to @rawuser, notice: 'Rawuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rawuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rawusers/1
  # DELETE /rawusers/1.json
  def destroy
    @rawuser = Rawuser.find(params[:id])
    @rawuser.destroy

    respond_to do |format|
      format.html { redirect_to rawusers_url }
      format.json { head :no_content }
    end
  end

  def import
    Rawuser.import("192.168.0.201")
    redirect_to :action => "index"
  end

  def syncpc
    Employee.synchronize(:to_pc)
    redirect_to "/employees"
  end
end

app/helpers/rawusers_helper.rb
module RawusersHelper
end

app/views/rawusers/_form.html.erb
  <div class="group">
    <%= f.label :_type, t("activerecord.attributes.rawuser._type", :default => " type"), :class => :label %>
    <%= f.text_field :_type, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :_id, t("activerecord.attributes.rawuser._id", :default => ""), :class => :label %>
    <%= f.text_field :_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :machine_code, t("activerecord.attributes.rawuser.machine_code", :default => "Machine code"), :class => :label %>
    <%= f.text_field :machine_code, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :enroll_number, t("activerecord.attributes.rawuser.enroll_number", :default => "Enroll number"), :class => :label %>
    <%= f.text_field :enroll_number, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :name, t("activerecord.attributes.rawuser.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :password, t("activerecord.attributes.rawuser.password", :default => "Password"), :class => :label %>
    <%= f.text_field :password, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), rawusers_path, :class => "text_button_padding link_button" %>
</div>

app/views/rawusers/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/rawusers/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List rawuser")}", rawusers_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_rawuser_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_rawuser_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Rawuser</h2>
    <div class="inner">
      <%= form_for @rawuser, :url => rawuser_path(@rawuser), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/rawusers/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List rawdata")}", rawdata_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.list", :default => "List rawuser")}", rawusers_path  %></li>
      <!--li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_rawuser_path %></li-->
    </ul>
  </div>
  <div class="content">
    <div class="control">
      <a href="/rawusers-sync-pc" class="button" title="Sync Machine rec with Employee rec">
        <img alt="Sync Machine rec with Employee rec" src="/images/web-app-theme/icons/table_refresh.png"> Sync
      </a>
      <a href="/rawusers-import" class="button">
        <img alt="Import" src="/images/web-app-theme/icons/table_import.png"> Import
      </a>
    </div>
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Rawusers</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">Machine</th>
          <th>Enroll Number</th>
          <th>Name</th>
          <th>Password</th>
          <th>Privilege</th>
          <th>Enabled</th>
          <!--th>
            <%= t("activerecord.attributes.rawuser._type", :default => t("activerecord.labels._type", :default => "_type")) %>
          </th-->
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @rawusers.each do |rawuser| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= rawuser.machine_code %>
          </td>
          <td>
            <%= rawuser.enroll_number %>
          </td>
          <td>
            <%= rawuser.name %>
          </td>
          <td>
            <%= rawuser.password %>
          </td>
          <td>
            <%= rawuser.privilege %>
          </td>
          <td>
            <%= rawuser.enabled %>
          </td>
          <!--td>
            <%= link_to rawuser._type, rawuser_path(rawuser) %>
          </td-->
          <td>
            <%= rawuser.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", rawuser_path(rawuser) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_rawuser_path(rawuser) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", rawuser_path(rawuser), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @rawusers  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/rawusers/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", rawusers_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_rawuser_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Rawuser</h2>
    <div class="inner">
      <%= form_for :rawuser, :url => rawusers_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/rawusers/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", rawusers_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_rawuser_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", rawuser_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.rawuser._type", :default => t("activerecord.labels._type", :default => " type")) %>:</b>
          <%= @rawuser._type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.rawuser._id", :default => t("activerecord.labels._id", :default => "")) %>:</b>
          <%= @rawuser._id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.rawuser.machine_code", :default => t("activerecord.labels.machine_code", :default => "Machine code")) %>:</b>
          <%= @rawuser.machine_code %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.rawuser.enroll_number", :default => t("activerecord.labels.enroll_number", :default => "Enroll number")) %>:</b>
          <%= @rawuser.enroll_number %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.rawuser.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @rawuser.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.rawuser.password", :default => t("activerecord.labels.password", :default => "Password")) %>:</b>
          <%= @rawuser.password %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_rawuser_path(@rawuser), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), rawuser_path(@rawuser), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>