config/routes.rb
Rails3MongoidDevise::Application.routes.draw do

  resources :dayoffs

  resources :rawusers

  resources :timesheets

  resources :rawdata

  resources :employees

  resources :departments

  resources :timeshifts

  match "/rawdata-import"           => "rawdata#import"
  match "/rawusers-import"          => "rawusers#import"
  match "/rawusers-sync-pc"         => "rawusers#syncpc"
  match "/settings"                 => "settings#show"
  match "/settings/departments"     => "settings#departments"
  match "/settings/timeshifts"      => "settings#timeshifts"
  match "/settings/dayoffs"         => "settings#dayoffs"
  match "/settings/messages"        => "settings#messages"


  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  root :to => "home#index"
  resources :users, :only => [:show, :index]
end

app/models/setting.rb
class Setting
  include Mongoid::Document
  field :name, type: String
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end

  def show
  end

  def departments
    @departments = Department.page(params[:page])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @departments }
    end
  end

  def timeshifts
    @timeshifts = Timeshift.page(params[:page])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeshifts }
    end
  end

  def dayoffs
    @dayoffs = Dayoff.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dayoffs }
    end
  end

  def messages
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/settings/dayoffs.html.erb
<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="/settings">Settings</a></li>
      <li><a href="/settings/departments">Departments</a></li>
      <li><a href="/settings/timeshifts">Timeshifts</a></li>
      <li class="active"><a href="/settings/dayoffs">Dayoffs</a></li>
      <li><a href="/settings/messages">Messages</a></li>
    </ul>
  </div>
  <div class="content">
    <div class="control">
      <a href="/dayoffs/new" class="button" title="New dayoff">
        <img alt="New department" src="/images/web-app-theme/icons/clock_add.png"> New
      </a>
    </div>
    <h2 class="title">Dayoffs</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>Name</th>
          <th>Type</th>
          <th>Occur</th>
          <th>Date</th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @dayoffs.each do |dayoff| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= dayoff._id %>
          </td>
          <td>
            <%= dayoff.name %>
          </td>
          <td>
            <%= dayoff.type %>
          </td>
          <td>
            <%= dayoff.occur %>
          </td>
          <td>
            <%= dayoff.date_s %>
          </td>
          <td>
            <%= dayoff.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", dayoff_path(dayoff) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_dayoff_path(dayoff) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", dayoff_path(dayoff), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @dayoffs  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/settings/departments.html.erb
<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="/settings">Settings</a></li>
      <li class="active"><a href="/settings/departments">Departments</a></li>
      <li><a href="/settings/timeshifts">Timeshifts</a></li>
      <li><a href="/settings/dayoffs">Dayoffs</a></li>
      <li><a href="/settings/messages">Messages</a></li>
    </ul>
  </div>
  <div class="content">
    <div class="control">
      <a href="/departments/new" class="button" title="New department">
        <img alt="New department" src="/images/web-app-theme/icons/chart_organisation_add.png"> New
      </a>
    </div>
    <h2 class="title">Department</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>Name</th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @departments.each do |depart| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= depart._id %>
          </td>
          <td>
            <%= depart.name %>
          </td>
          <td>
            <%= depart.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", department_path(depart) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_department_path(depart) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", department_path(depart), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @departments  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/settings/index.html.erb
<h1>Settings#index</h1>
<p>Find me in app/views/settings/index.html.erb</p>

app/views/settings/messages.html.erb
<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="/settings">Settings</a></li>
      <li><a href="/settings/departments">Departments</a></li>
      <li><a href="/settings/timeshifts">Timeshifts</a></li>
      <li><a href="/settings/dayoffs">Dayoffs</a></li>
      <li class="active"><a href="/settings/messages">Messages</a></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Messages</h2>
    <div class="inner">
      <p class="first">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <p> <span class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <p> <span class="gray">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <hr />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/settings/show.html.erb
<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="active first"><a href="/settings">Settings</a></li>
      <li><a href="/settings/departments">Departments</a></li>
      <li><a href="/settings/timeshifts">Timeshifts</a></li>
      <li><a href="/settings/dayoffs">Dayoffs</a></li>
      <li><a href="/settings/messages">Messages</a></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Settings</h2>
    <div class="inner">
      <!--
      <p class="first">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <p> <span class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <p> <span class="gray">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <hr />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      -->
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/settings/timelot.html.erb
<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="/settings">Settings</a></li>
      <li><a href="/settings/department">Department</a></li>
      <li><a href="/settings/timeshift">Time shift</a></li>
      <li class="active"><a href="/settings/timelot">Time lot</a></li>
      <li><a href="/settings/messages">Messages</a></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title">Time lot</h2>
    <div class="inner">
      <p class="first">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
      <p> <span class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <p> <span class="gray">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore</span></p>
      <hr />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. <span class="hightlight">Excepteur sint occaecat cupidatat non proident</span>, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/settings/timeshifts.html.erb
<div class="block" id="block-text">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="/settings">Settings</a></li>
      <li><a href="/settings/departments">Departments</a></li>
      <li class="active"><a href="/settings/timeshifts">Timeshifts</a></li>
      <li><a href="/settings/dayoffs">Dayoffs</a></li>
      <li><a href="/settings/messages">Messages</a></li>
    </ul>
  </div>
  <div class="content">
    <div class="control">
      <a href="/timeshifts/new" class="button" title="New timeshift">
        <img alt="New department" src="/images/web-app-theme/icons/clock_add.png"> New
      </a>
    </div>
    <h2 class="title">Timeshifts</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th style="width:100px">Name</th>
          <th>In/out</th>
          <th>Break In/out</th>
          <th style="width:100px">Begin/End In/out</th>
          <th style="width:100px">Options</th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last" style="width:120px">&nbsp;</th>
        </tr>
        <% @timeshifts.each do |timeshift| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= timeshift._id %>
          </td>
          <td>
            <%= timeshift.name %>
          </td>
          <td>
            <%= timeshift.ts_time_s %>
          </td>
          <td>
            <%= timeshift.break_time_s %>
          </td>
          <td>
            <%= timeshift.in_time_s + timeshift.out_time_s %>
          </td>
          <td>
          </td>
          <td>
            <%= distance_of_time_in_words_to_now(timeshift.created_at) %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", timeshift_path(timeshift) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_timeshift_path(timeshift) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", timeshift_path(timeshift), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @timeshifts  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>