config/routes.rb
Rails3MongoidDevise::Application.routes.draw do

  resources :dayoffs

  resources :rawusers

  resources :timesheets

  resources :rawdata

  resources :employees

  resources :departments

  resources :timeshifts

  match "/rawdata-import"           => "rawdata#import"
  match "/rawusers-import"          => "rawusers#import"
  match "/rawusers-sync-pc"         => "rawusers#syncpc"
  match "/settings"                 => "settings#show"
  match "/settings/departments"     => "settings#departments"
  match "/settings/timeshifts"      => "settings#timeshifts"
  match "/settings/dayoffs"         => "settings#dayoffs"
  match "/settings/messages"        => "settings#messages"


  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  root :to => "home#index"
  resources :users, :only => [:show, :index]
end

app/models/dayoff.rb
class Dayoff
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  include Mongoid::Timestamps::Created
  
  paginates_per 5

  OCCUR_TYPES = [:yearly, :monthly, :once]
  OCCUR_FORMATS = { :yearly => "%m-%d", :monthly => "%d", :once => "%Y-%m-%d" }

  field :name, type: String
  field :type, type: String
  field :occur, type: Symbol
  field :date, type: Date

  validates_presence_of :name
  validates_presence_of :type
  validates_presence_of :occur

  def date_s
    return false if !date?
    date.strftime(OCCUR_FORMATS[occur])
  end

  OCCUR_TYPES.each do |type|
    scope "#{type}_days", where("occur" => type)
  end

  def off?(date, format)
    self.date.strftime(format) == date.strftime(format)
  end

  class << self
    def by_date(date)
      OCCUR_TYPES.each do |type|
        send("#{type}_days").each do |d| 
          return d if d.off?(date, OCCUR_FORMATS[type])
        end
      end
      nil
    end

    def offday?(date)
      return true if by_date(date)
      false
    end
  end
end

app/controllers/dayoffs_controller.rb
class DayoffsController < ApplicationController
  # GET /dayoffs
  # GET /dayoffs.json
  def index
    redirect_to "/settings/dayoffs"
  end

  # GET /dayoffs/1
  # GET /dayoffs/1.json
  def show
    @dayoff = Dayoff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dayoff }
    end
  end

  # GET /dayoffs/new
  # GET /dayoffs/new.json
  def new
    @dayoff = Dayoff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dayoff }
    end
  end

  # GET /dayoffs/1/edit
  def edit
    @dayoff = Dayoff.find(params[:id])
  end

  # POST /dayoffs
  # POST /dayoffs.json
  def create
    @dayoff = Dayoff.new(params[:dayoff])

    respond_to do |format|
      if @dayoff.save
        format.html { redirect_to @dayoff, notice: 'Dayoff was successfully created.' }
        format.json { render json: @dayoff, status: :created, location: @dayoff }
      else
        format.html { render action: "new" }
        format.json { render json: @dayoff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dayoffs/1
  # PUT /dayoffs/1.json
  def update
    @dayoff = Dayoff.find(params[:id])

    respond_to do |format|
      if @dayoff.update_attributes(params[:dayoff])
        format.html { redirect_to @dayoff, notice: 'Dayoff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dayoff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dayoffs/1
  # DELETE /dayoffs/1.json
  def destroy
    @dayoff = Dayoff.find(params[:id])
    @dayoff.destroy

    respond_to do |format|
      format.html { redirect_to dayoffs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dayoffs_helper.rb
module DayoffsHelper
end

app/views/dayoffs/_form.html.erb
<div class="group">
  <%= f.label :name, t("activerecord.attributes.dayoff.name", :default => "Name"), :class => :label %>
  <%= f.text_field :name, :class => 'text_field' %>
</div>
<div class="columns wat-cf">
  <div class="column left">
    <div class="group">
      <%= f.label :type, t("activerecord.attributes.dayoff.type", :default => "Type"), :class => :label %>
      <%#= f.text_field :type, :class => 'text_field' %>
      <div style="width:30%; float: left;">
      <%= f.radio_button :type, "holiday", :class => "radio" %>
      <%= label_tag :dayoff_type_holiday, "Holiday" %>
      </div>
      <div style="">
      <%= f.radio_button :type, "company", :class => "radio" %>
      <%= label_tag :dayoff_type_company, "Company" %>
      </div>
    </div>
    <div class="group">
      <%= f.label :date, t("activerecord.attributes.dayoff.date", :default => "Date"), :class => :label %>
      <%= f.date_select :date, :prompt => { :day => 'Select day', :month => 'Select month', :year => 'Select year' } %>
    </div>
  </div>
  <div class="column right">
    <div class="group">
      <%= f.label :occur, t("activerecord.attributes.dayoff.occur", :default => "Occurrence"), :class => :label %>
      <div style="width:30%; float: left;">
      <%= f.radio_button :occur, "once", :class => "radio" %>
      <%= label_tag :dayoff_occur_once, "Once Time" %>
      </div>
      <div style="width:30%; float: left;">
      <%= f.radio_button :occur, "yearly", :class => "radio" %>
      <%= label_tag :dayoff_occur_yearly, "Yearly" %>
      </div>
      <div style="">
      <%= f.radio_button :occur, "monthly", :class => "radio" %>
      <%= label_tag :dayoff_occur_monthly, "Monthly" %>
      </div>
    </div>
  </div>
</div>
<br/>
<div class="group navform wat-cf">  
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
  <%= link_to t("web-app-theme.cancel", :default => "Cancel"), dayoffs_path, :class => "text_button_padding link_button" %>
</div>

app/views/dayoffs/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/dayoffs/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", dayoffs_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dayoff_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_dayoff_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Department</h2>
    <div class="inner">
      <%= form_for @dayoff, :url => dayoff_path(@dayoff), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/dayoffs/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", departments_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_department_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Employees</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>Name</th>
          <th>Gender</th>
          <th>Department</th>
          <th>Enroll Number</th>
          <!--th>
            <%= t("activerecord.attributes.department._type", :default => t("activerecord.labels._type", :default => "_type")) %>
          </th-->
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @departments.each do |department| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= department.id %>
          </td>
          <td>
            <%= department.name %>
          </td>
          <td>
            <%= department.gender %>
          </td>
          <td>
            <%= department.department %>
          </td>
          <td>
            <%= department.enroll_number %>
          </td>
          <!--td>
            <%= link_to department._type, department_path(department) %>
          </td-->
          <td>
            <%= department.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", department_path(department) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_department_path(department) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", department_path(department), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= paginate @departments  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/dayoffs/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", "/settings/dayoffs"  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dayoff_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Dayoff</h2>
    <div class="inner">
      <%= form_for :dayoff, :url => dayoffs_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/dayoffs/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", "/settings/dayoffs"  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_dayoff_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", dayoff_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.dayoff._type", :default => t("activerecord.labels._type", :default => " type")) %>:</b>
          <%= @dayoff._type %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.dayoff._id", :default => t("activerecord.labels._id", :default => "")) %>:</b>
          <%= @dayoff._id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.dayoff.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @dayoff.name %>
        </p>

      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_dayoff_path(@dayoff), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), dayoff_path(@dayoff), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>